In [4]:
import pandas as pd
df=pd.read_csv("IPL IMB381IPL2013.csv")
(df)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0.00,0,307,15,20.47,8.90,13.93,2009,50000,50000
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0.00,0,29,0,0.00,14.50,0.00,2008,50000,50000
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,121.01,5,1059,29,36.52,8.81,24.90,2008,200000,350000
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,76.32,0,1125,49,22.96,6.23,22.14,2011,100000,850000
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,120.71,28,0,0,0.00,0.00,0.00,2011,100000,800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,126,"Yadav, AS",2,IND,DC,Batsman,0,0,0,0.00,...,125.64,2,0,0,0.00,0.00,0.00,2010,50000,750000
126,127,Younis Khan,2,PAK,RR,Batsman,6398,7,6814,75.78,...,42.85,0,0,0,0.00,0.00,0.00,2008,225000,225000
127,128,Yuvraj Singh,2,IND,KXIP+,Batsman,1775,9,8051,87.58,...,131.88,67,569,23,24.74,7.02,21.13,2011,400000,1800000
128,129,Zaheer Khan,2,IND,MI+,Bowler,1114,288,790,73.55,...,91.67,1,1783,65,27.43,7.75,21.26,2008,200000,450000
129,130,"Zoysa, DNT",2,SL,DC,Bowler,288,64,343,95.81,...,122.22,0,99,2,49.50,9.00,33.00,2008,100000,110000

In [5]:
df.head(10)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0.00,0,307,15,20.47,8.90,13.93,2009,50000,50000
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0.00,0,29,0,0.00,14.50,0.00,2008,50000,50000
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,121.01,5,1059,29,36.52,8.81,24.90,2008,200000,350000
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,76.32,0,1125,49,22.96,6.23,22.14,2011,100000,850000
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,120.71,28,0,0,0.00,0.00,0.00,2011,100000,800000
5,6,"Bailey, GJ",2,AUS,CSK,Batsman,0,0,172,72.26,...,95.45,0,0,0,0.00,0.00,0.00,2009,50000,50000
6,7,"Balaji, L",2,IND,CSK+,Bowler,51,27,120,78.94,...,72.22,1,1342,52,25.81,7.98,19.40,2011,100000,500000
7,8,"Bollinger, DE",2,AUS,CSK,Bowler,54,50,50,92.59,...,165.88,1,693,37,18.73,7.22,15.57,2011,200000,700000
8,9,"Botha, J",2,SA,RR,Allrounder,83,17,609,85.77,...,114.73,3,610,19,32.11,6.85,28.11,2011,200000,950000
9,10,"Boucher, MV",2,SA,RCB+,W. Keeper,5515,1,4686,84.76,...,127.51,13,0,0,0.00,0.00,0.00,2008,200000,450000

In [6]:
df.tail(10)

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
120,121,"Vettori, DL",2,NZ,DD+,Allrounder,4486,359,2105,81.93,...,107.08,2,878,28,31.36,6.81,27.75,2008,250000,625000
121,122,"Vinay Kumar, R",2,IND,RCB+,Bowler,11,1,43,43.87,...,104.83,5,1664,61,27.28,8.24,19.87,2011,100000,475000
122,123,"Warne, SK",3,AUS,RR,Bowler,3154,708,1018,72.04,...,92.52,6,1447,57,25.39,7.27,20.95,2008,450000,450000
123,124,"Warner, DA",1,AUS,DD,Batsman,483,2,876,85.79,...,135.76,44,0,0,0.00,0.00,0.00,2011,200000,750000
124,125,"White, CL",2,AUS,RCB+,Batsman,146,5,2037,80.48,...,132.09,29,70,0,0.00,14.00,0.00,2008,100000,500000
125,126,"Yadav, AS",2,IND,DC,Batsman,0,0,0,0.00,...,125.64,2,0,0,0.00,0.00,0.00,2010,50000,750000
126,127,Younis Khan,2,PAK,RR,Batsman,6398,7,6814,75.78,...,42.85,0,0,0,0.00,0.00,0.00,2008,225000,225000
127,128,Yuvraj Singh,2,IND,KXIP+,Batsman,1775,9,8051,87.58,...,131.88,67,569,23,24.74,7.02,21.13,2011,400000,1800000
128,129,Zaheer Khan,2,IND,MI+,Bowler,1114,288,790,73.55,...,91.67,1,1783,65,27.43,7.75,21.26,2008,200000,450000
129,130,"Zoysa, DNT",2,SL,DC,Bowler,288,64,343,95.81,...,122.22,0,99,2,49.50,9.00,33.00,2008,100000,110000

In [7]:
print(list(df.columns))

['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE', 'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL', 'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C', 'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE', 'SOLD PRICE']

In [8]:
df.shape

(130, 26)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl.NO.         130 non-null    int64
 1   PLAYER NAME    130 non-null    object
 2   AGE            130 non-null    int64
 3   COUNTRY        130 non-null    object
 4   TEAM           130 non-null    object
 5   PLAYING ROLE   130 non-null    object
 6   T-RUNS         130 non-null    int64
 7   T-WKTS         130 non-null    int64
 8   ODI-RUNS-S     130 non-null    int64
 9   ODI-SR-B       130 non-null    float64
 10  ODI-WKTS       130 non-null    int64
 11  ODI-SR-BL      130 non-null    float64
 12  CAPTAINCY EXP  130 non-null    int64
 13  RUNS-S         130 non-null    int64
 14  HS             130 non-null    int64
 15  AVE            130 non-null    float64
 16  SR-B           130 non-null    float64
 17  SIXERS         130 non-null    int64
 18  RUNS-C         130 non-null    int64
 19  WKTS           130 non-null    int64
 20  AVE-BL         130 non-null    float64
 21  ECON           130 non-null    float64
 22  SR-BL          130 non-null    float64
 23  AUCTION YEAR   130 non-null    int64
 24  BASE PRICE     130 non-null    int64
 25  SOLD PRICE     130 non-null    int64
dtypes: float64(7), int64(15), object(4)
memory usage: 26.5+ KB

In [10]:
df.loc[0:9]

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0.00,0,307,15,20.47,8.90,13.93,2009,50000,50000
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0.00,0,29,0,0.00,14.50,0.00,2008,50000,50000
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,121.01,5,1059,29,36.52,8.81,24.90,2008,200000,350000
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,76.32,0,1125,49,22.96,6.23,22.14,2011,100000,850000
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,120.71,28,0,0,0.00,0.00,0.00,2011,100000,800000
5,6,"Bailey, GJ",2,AUS,CSK,Batsman,0,0,172,72.26,...,95.45,0,0,0,0.00,0.00,0.00,2009,50000,50000
6,7,"Balaji, L",2,IND,CSK+,Bowler,51,27,120,78.94,...,72.22,1,1342,52,25.81,7.98,19.40,2011,100000,500000
7,8,"Bollinger, DE",2,AUS,CSK,Bowler,54,50,50,92.59,...,165.88,1,693,37,18.73,7.22,15.57,2011,200000,700000
8,9,"Botha, J",2,SA,RR,Allrounder,83,17,609,85.77,...,114.73,3,610,19,32.11,6.85,28.11,2011,200000,950000
9,10,"Boucher, MV",2,SA,RCB+,W. Keeper,5515,1,4686,84.76,...,127.51,13,0,0,0.00,0.00,0.00,2008,200000,450000

In [11]:
df.loc[0:10]

,Sl.NO.,PLAYER NAME,AGE,COUNTRY,TEAM,PLAYING ROLE,T-RUNS,T-WKTS,ODI-RUNS-S,ODI-SR-B,...,SR-B,SIXERS,RUNS-C,WKTS,AVE-BL,ECON,SR-BL,AUCTION YEAR,BASE PRICE,SOLD PRICE
0,1,"Abdulla, YA",2,SA,KXIP,Allrounder,0,0,0,0.00,...,0.00,0,307,15,20.47,8.90,13.93,2009,50000,50000
1,2,Abdur Razzak,2,BAN,RCB,Bowler,214,18,657,71.41,...,0.00,0,29,0,0.00,14.50,0.00,2008,50000,50000
2,3,"Agarkar, AB",2,IND,KKR,Bowler,571,58,1269,80.62,...,121.01,5,1059,29,36.52,8.81,24.90,2008,200000,350000
3,4,"Ashwin, R",1,IND,CSK,Bowler,284,31,241,84.56,...,76.32,0,1125,49,22.96,6.23,22.14,2011,100000,850000
4,5,"Badrinath, S",2,IND,CSK,Batsman,63,0,79,45.93,...,120.71,28,0,0,0.00,0.00,0.00,2011,100000,800000
5,6,"Bailey, GJ",2,AUS,CSK,Batsman,0,0,172,72.26,...,95.45,0,0,0,0.00,0.00,0.00,2009,50000,50000
6,7,"Balaji, L",2,IND,CSK+,Bowler,51,27,120,78.94,...,72.22,1,1342,52,25.81,7.98,19.40,2011,100000,500000
7,8,"Bollinger, DE",2,AUS,CSK,Bowler,54,50,50,92.59,...,165.88,1,693,37,18.73,7.22,15.57,2011,200000,700000
8,9,"Botha, J",2,SA,RR,Allrounder,83,17,609,85.77,...,114.73,3,610,19,32.11,6.85,28.11,2011,200000,950000
9,10,"Boucher, MV",2,SA,RCB+,W. Keeper,5515,1,4686,84.76,...,127.51,13,0,0,0.00,0.00,0.00,2008,200000,450000
10,11,"Bravo, DJ",2,WI,MI+,Allrounder,2200,86,2004,81.39,...,127.12,38,1338,47,28.47,8.12,21.11,2011,200000,200000

df.loc[1]

In [12]:
df.loc[1]

Sl.NO.                      2
PLAYER NAME      Abdur Razzak
AGE                         2
COUNTRY                   BAN
TEAM                      RCB
PLAYING ROLE           Bowler
T-RUNS                    214
T-WKTS                     18
ODI-RUNS-S                657
ODI-SR-B                71.41
ODI-WKTS                  185
ODI-SR-BL                37.6
CAPTAINCY EXP               0
RUNS-S                      0
HS                          0
AVE                       0.0
SR-B                      0.0
SIXERS                      0
RUNS-C                     29
WKTS                        0
AVE-BL                    0.0
ECON                     14.5
SR-BL                     0.0
AUCTION YEAR             2008
BASE PRICE              50000
SOLD PRICE              50000
Name: 1, dtype: object

In [13]:
df.loc[2]

Sl.NO.                     3
PLAYER NAME      Agarkar, AB
AGE                        2
COUNTRY                  IND
TEAM                     KKR
PLAYING ROLE          Bowler
T-RUNS                   571
T-WKTS                    58
ODI-RUNS-S              1269
ODI-SR-B               80.62
ODI-WKTS                 288
ODI-SR-BL               32.9
CAPTAINCY EXP              0
RUNS-S                   167
HS                        39
AVE                    18.56
SR-B                  121.01
SIXERS                     5
RUNS-C                  1059
WKTS                      29
AVE-BL                 36.52
ECON                    8.81
SR-BL                   24.9
AUCTION YEAR            2008
BASE PRICE            200000
SOLD PRICE            350000
Name: 2, dtype: object

In [14]:
df[["PLAYER NAME","COUNTRY"]]

      PLAYER NAME COUNTRY
0     Abdulla, YA      SA
1    Abdur Razzak     BAN
2     Agarkar, AB     IND
3       Ashwin, R     IND
4    Badrinath, S     IND
..            ...     ...
125     Yadav, AS     IND
126   Younis Khan     PAK
127  Yuvraj Singh     IND
128   Zaheer Khan     IND
129    Zoysa, DNT      SL

[130 rows x 2 columns]

In [15]:
df.columns

Index(['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE',
       'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL',
       'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C',
       'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE',
       'SOLD PRICE'],
      dtype='object')

In [16]:
df.index

RangeIndex(start=0, stop=130, step=1)

In [17]:
df.describe

<bound method NDFrame.describe of      Sl.NO.   PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0         1   Abdulla, YA    2      SA   KXIP   Allrounder       0       0
1         2  Abdur Razzak    2     BAN    RCB       Bowler     214      18
2         3   Agarkar, AB    2     IND    KKR       Bowler     571      58
3         4     Ashwin, R    1     IND    CSK       Bowler     284      31
4         5  Badrinath, S    2     IND    CSK      Batsman      63       0
..      ...           ...  ...     ...    ...          ...     ...     ...
125     126     Yadav, AS    2     IND     DC      Batsman       0       0
126     127   Younis Khan    2     PAK     RR      Batsman    6398       7
127     128  Yuvraj Singh    2     IND  KXIP+      Batsman    1775       9
128     129   Zaheer Khan    2     IND    MI+       Bowler    1114     288
129     130    Zoysa, DNT    2      SL     DC       Bowler     288      64

     ODI-RUNS-S  ODI-SR-B  ...    SR-B  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  \
0             0      0.00  ...    0.00       0     307    15   20.47   8.90
1           657     71.41  ...    0.00       0      29     0    0.00  14.50
2          1269     80.62  ...  121.01       5    1059    29   36.52   8.81
3           241     84.56  ...   76.32       0    1125    49   22.96   6.23
4            79     45.93  ...  120.71      28       0     0    0.00   0.00
..          ...       ...  ...     ...     ...     ...   ...     ...    ...
125           0      0.00  ...  125.64       2       0     0    0.00   0.00
126        6814     75.78  ...   42.85       0       0     0    0.00   0.00
127        8051     87.58  ...  131.88      67     569    23   24.74   7.02
128         790     73.55  ...   91.67       1    1783    65   27.43   7.75
129         343     95.81  ...  122.22       0      99     2   49.50   9.00

     SR-BL  AUCTION YEAR  BASE PRICE  SOLD PRICE
0    13.93          2009       50000       50000
1     0.00          2008       50000       50000
2    24.90          2008      200000      350000
3    22.14          2011      100000      850000
4     0.00          2011      100000      800000
..     ...           ...         ...         ...
125   0.00          2010       50000      750000
126   0.00          2008      225000      225000
127  21.13          2011      400000     1800000
128  21.26          2008      200000      450000
129  33.00          2008      100000      110000

[130 rows x 26 columns]>

In [18]:
df.iloc[4:1,1:4]

Empty DataFrame
Columns: [PLAYER NAME, AGE, COUNTRY]
Index: []

In [21]:
s_age=df.groupby('AGE')['SOLD PRICE'].mean()
s_age

AGE
1    720250.000000
2    484534.883721
3    520178.571429
Name: SOLD PRICE, dtype: float64

In [20]:
df.columns

Index(['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE',
       'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL',
       'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C',
       'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE',
       'SOLD PRICE'],
      dtype='object')

In [22]:
df["AGE"]

0      2
1      2
2      2
3      1
4      2
      ..
125    2
126    2
127    2
128    2
129    2
Name: AGE, Length: 130, dtype: int64

In [30]:
print(df.groupby('AGE'))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000020DE6744B50>

In [27]:
s_age=df.groupby('AGE')['SOLD PRICE'].mean().reset_index()

In [29]:
s_age=df.groupby('AGE')['SOLD PRICE'].mean().reset_index()
s_age

   AGE     SOLD PRICE
0    1  720250.000000
1    2  484534.883721
2    3  520178.571429

In [31]:
df['PREMIUM']=df['SOLD PRICE']-df['BASE PRICE']

In [33]:
df['PREMIUM']=df['SOLD PRICE']-df['BASE PRICE']
df['PREMIUM']

0            0
1            0
2       150000
3       750000
4       700000
        ...
125     700000
126          0
127    1400000
128     250000
129      10000
Name: PREMIUM, Length: 130, dtype: int64